export { default as Navbar } from './Navbar/Navbar';
export { default as Loader } from './Loader/Loader';
export { default as Button } from './Button/Button';
export { default as Input } from './Input/Input';
export { default as Clues } from './Clues/Clues';
export { default as Question } from './Question/Question';
export { default as Timer } from './Timer/Timer';
export { default as Topics } from './Topics/Topics';
// export { default as  } from '';
